// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlite

import (
	"context"
	"database/sql"
	"time"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}

const addNewContentFile = `-- name: AddNewContentFile :one
INSERT INTO content_library (
    media_library_id,
    created_at,
    file_path,
    name,
    media_title,
    description,
    cover_url,
    parent_id,
    external_provider,
    external_provider_id,
    media_type,
    classifier
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, media_library_id, created_at, file_path, name, media_title, description, cover_url, parent_id, classifier, media_type, external_provider, external_provider_id
`

type AddNewContentFileParams struct {
	MediaLibraryID     int64
	CreatedAt          time.Time
	FilePath           string
	Name               string
	MediaTitle         string
	Description        sql.NullString
	CoverUrl           sql.NullString
	ParentID           sql.NullInt64
	ExternalProvider   sql.NullString
	ExternalProviderID sql.NullInt64
	MediaType          string
	Classifier         string
}

func (q *Queries) AddNewContentFile(ctx context.Context, arg AddNewContentFileParams) (ContentLibrary, error) {
	row := q.db.QueryRowContext(ctx, addNewContentFile,
		arg.MediaLibraryID,
		arg.CreatedAt,
		arg.FilePath,
		arg.Name,
		arg.MediaTitle,
		arg.Description,
		arg.CoverUrl,
		arg.ParentID,
		arg.ExternalProvider,
		arg.ExternalProviderID,
		arg.MediaType,
		arg.Classifier,
	)
	var i ContentLibrary
	err := row.Scan(
		&i.ID,
		&i.MediaLibraryID,
		&i.CreatedAt,
		&i.FilePath,
		&i.Name,
		&i.MediaTitle,
		&i.Description,
		&i.CoverUrl,
		&i.ParentID,
		&i.Classifier,
		&i.MediaType,
		&i.ExternalProvider,
		&i.ExternalProviderID,
	)
	return i, err
}

const createMediaLibrary = `-- name: CreateMediaLibrary :one
INSERT INTO media_library(created_at, name, description, device_path, media_type, owner_id) 
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, created_at, name, description, device_path, media_type, owner_id
`

type CreateMediaLibraryParams struct {
	CreatedAt   time.Time
	Name        string
	Description string
	DevicePath  string
	MediaType   string
	OwnerID     int64
}

func (q *Queries) CreateMediaLibrary(ctx context.Context, arg CreateMediaLibraryParams) (MediaLibrary, error) {
	row := q.db.QueryRowContext(ctx, createMediaLibrary,
		arg.CreatedAt,
		arg.Name,
		arg.Description,
		arg.DevicePath,
		arg.MediaType,
		arg.OwnerID,
	)
	var i MediaLibrary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.DevicePath,
		&i.MediaType,
		&i.OwnerID,
	)
	return i, err
}

const createProfile = `-- name: CreateProfile :exec
INSERT INTO profiles (username, password, type) 
VALUES ( ?, ?, ? )
`

type CreateProfileParams struct {
	Username string
	Password []byte
	Type     int64
}

func (q *Queries) CreateProfile(ctx context.Context, arg CreateProfileParams) error {
	_, err := q.db.ExecContext(ctx, createProfile, arg.Username, arg.Password, arg.Type)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, created_at, access_token, refresh_token, refresh_expires_at, access_expires_at, device, device_name, client_name, client_version)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, user_id, access_token, refresh_token, created_at, access_expires_at, refresh_expires_at, device, device_name, client_name, client_version
`

type CreateSessionParams struct {
	ID               string
	UserID           int64
	CreatedAt        time.Time
	AccessToken      string
	RefreshToken     string
	RefreshExpiresAt time.Time
	AccessExpiresAt  time.Time
	Device           string
	DeviceName       string
	ClientName       string
	ClientVersion    string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.AccessToken,
		arg.RefreshToken,
		arg.RefreshExpiresAt,
		arg.AccessExpiresAt,
		arg.Device,
		arg.DeviceName,
		arg.ClientName,
		arg.ClientVersion,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.Device,
		&i.DeviceName,
		&i.ClientName,
		&i.ClientVersion,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, access_token, refresh_token, created_at, access_expires_at, refresh_expires_at, device, device_name, client_name, client_version FROM sessions
WHERE id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.Device,
		&i.DeviceName,
		&i.ClientName,
		&i.ClientVersion,
	)
	return i, err
}

const getAdminUser = `-- name: GetAdminUser :one
SELECT id, username, password, type FROM profiles
WHERE type = 0
`

func (q *Queries) GetAdminUser(ctx context.Context) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getAdminUser)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Type,
	)
	return i, err
}

const getAllContentFiles = `-- name: GetAllContentFiles :many
SELECT id, media_library_id, created_at, file_path, name, media_title, description, cover_url, parent_id, classifier, media_type, external_provider, external_provider_id FROM content_library
WHERE media_library_id = ?
`

func (q *Queries) GetAllContentFiles(ctx context.Context, mediaLibraryID int64) ([]ContentLibrary, error) {
	rows, err := q.db.QueryContext(ctx, getAllContentFiles, mediaLibraryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentLibrary
	for rows.Next() {
		var i ContentLibrary
		if err := rows.Scan(
			&i.ID,
			&i.MediaLibraryID,
			&i.CreatedAt,
			&i.FilePath,
			&i.Name,
			&i.MediaTitle,
			&i.Description,
			&i.CoverUrl,
			&i.ParentID,
			&i.Classifier,
			&i.MediaType,
			&i.ExternalProvider,
			&i.ExternalProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllMediaLibraries = `-- name: GetAllMediaLibraries :many
SELECT id, created_at, name, description, device_path, media_type, owner_id FROM media_library
`

func (q *Queries) GetAllMediaLibraries(ctx context.Context) ([]MediaLibrary, error) {
	rows, err := q.db.QueryContext(ctx, getAllMediaLibraries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaLibrary
	for rows.Next() {
		var i MediaLibrary
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Name,
			&i.Description,
			&i.DevicePath,
			&i.MediaType,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllShows = `-- name: GetAllShows :many
SELECT id, media_library_id, created_at, file_path, name, media_title, description, cover_url, parent_id, classifier, media_type, external_provider, external_provider_id FROM content_library
WHERE media_library_id = ? AND media_type = ?
`

type GetAllShowsParams struct {
	MediaLibraryID int64
	MediaType      string
}

func (q *Queries) GetAllShows(ctx context.Context, arg GetAllShowsParams) ([]ContentLibrary, error) {
	rows, err := q.db.QueryContext(ctx, getAllShows, arg.MediaLibraryID, arg.MediaType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentLibrary
	for rows.Next() {
		var i ContentLibrary
		if err := rows.Scan(
			&i.ID,
			&i.MediaLibraryID,
			&i.CreatedAt,
			&i.FilePath,
			&i.Name,
			&i.MediaTitle,
			&i.Description,
			&i.CoverUrl,
			&i.ParentID,
			&i.Classifier,
			&i.MediaType,
			&i.ExternalProvider,
			&i.ExternalProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContentFromExternalId = `-- name: GetContentFromExternalId :one
SELECT id, media_library_id, created_at, file_path, name, media_title, description, cover_url, parent_id, classifier, media_type, external_provider, external_provider_id FROM content_library
WHERE external_provider_id = ?
`

func (q *Queries) GetContentFromExternalId(ctx context.Context, externalProviderID sql.NullInt64) (ContentLibrary, error) {
	row := q.db.QueryRowContext(ctx, getContentFromExternalId, externalProviderID)
	var i ContentLibrary
	err := row.Scan(
		&i.ID,
		&i.MediaLibraryID,
		&i.CreatedAt,
		&i.FilePath,
		&i.Name,
		&i.MediaTitle,
		&i.Description,
		&i.CoverUrl,
		&i.ParentID,
		&i.Classifier,
		&i.MediaType,
		&i.ExternalProvider,
		&i.ExternalProviderID,
	)
	return i, err
}

const getContentFromParentId = `-- name: GetContentFromParentId :many
SELECT id, media_library_id, created_at, file_path, name, media_title, description, cover_url, parent_id, classifier, media_type, external_provider, external_provider_id FROM content_library
WHERE parent_id = ?
`

func (q *Queries) GetContentFromParentId(ctx context.Context, parentID sql.NullInt64) ([]ContentLibrary, error) {
	rows, err := q.db.QueryContext(ctx, getContentFromParentId, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContentLibrary
	for rows.Next() {
		var i ContentLibrary
		if err := rows.Scan(
			&i.ID,
			&i.MediaLibraryID,
			&i.CreatedAt,
			&i.FilePath,
			&i.Name,
			&i.MediaTitle,
			&i.Description,
			&i.CoverUrl,
			&i.ParentID,
			&i.Classifier,
			&i.MediaType,
			&i.ExternalProvider,
			&i.ExternalProviderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getContentFromPath = `-- name: GetContentFromPath :one
SELECT id, media_library_id, created_at, file_path, name, media_title, description, cover_url, parent_id, classifier, media_type, external_provider, external_provider_id FROM content_library
WHERE file_path = ?
`

func (q *Queries) GetContentFromPath(ctx context.Context, filePath string) (ContentLibrary, error) {
	row := q.db.QueryRowContext(ctx, getContentFromPath, filePath)
	var i ContentLibrary
	err := row.Scan(
		&i.ID,
		&i.MediaLibraryID,
		&i.CreatedAt,
		&i.FilePath,
		&i.Name,
		&i.MediaTitle,
		&i.Description,
		&i.CoverUrl,
		&i.ParentID,
		&i.Classifier,
		&i.MediaType,
		&i.ExternalProvider,
		&i.ExternalProviderID,
	)
	return i, err
}

const getContentByID = `-- name: GetContentByID :one
SELECT id, media_library_id, created_at, file_path, name, media_title, description, cover_url, parent_id, classifier, media_type, external_provider, external_provider_id FROM content_library
WHERE id = ?
`

func (q *Queries) GetContentByID(ctx context.Context, id int64) (ContentLibrary, error) {
	row := q.db.QueryRowContext(ctx, getContentByID, id)
	var i ContentLibrary
	err := row.Scan(
		&i.ID,
		&i.MediaLibraryID,
		&i.CreatedAt,
		&i.FilePath,
		&i.Name,
		&i.MediaTitle,
		&i.Description,
		&i.CoverUrl,
		&i.ParentID,
		&i.Classifier,
		&i.MediaType,
		&i.ExternalProvider,
		&i.ExternalProviderID,
	)
	return i, err
}

const getMediaLibrary = `-- name: GetMediaLibrary :one
SELECT id, created_at, name, description, device_path, media_type, owner_id FROM media_library
WHERE id = ?
`

func (q *Queries) GetMediaLibrary(ctx context.Context, id int64) (MediaLibrary, error) {
	row := q.db.QueryRowContext(ctx, getMediaLibrary, id)
	var i MediaLibrary
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Name,
		&i.Description,
		&i.DevicePath,
		&i.MediaType,
		&i.OwnerID,
	)
	return i, err
}

const getProfiles = `-- name: GetProfiles :many
SELECT id, username, password, type FROM profiles
`

func (q *Queries) GetProfiles(ctx context.Context) ([]Profile, error) {
	rows, err := q.db.QueryContext(ctx, getProfiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Profile
	for rows.Next() {
		var i Profile
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserFromUsername = `-- name: GetUserFromUsername :one
SELECT id, username, password, type FROM profiles 
WHERE username = ?
`

func (q *Queries) GetUserFromUsername(ctx context.Context, username string) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getUserFromUsername, username)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Type,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, password, type FROM profiles 
WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (Profile, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i Profile
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Type,
	)
	return i, err
}

const isFinishedSetup = `-- name: IsFinishedSetup :one
SELECT count(*) FROM profiles
`

func (q *Queries) IsFinishedSetup(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, isFinishedSetup)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE profiles 
SET username = ?, password = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Username string
	Password []byte
	ID       int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Username, arg.Password, arg.ID)
	return err
}
